#!/bin/bash

#SBATCH --job-name=JOB_NAME # The job name # CHANGE
#SBATCH --export=NONE               # Start with a clean environment
#SBATCH --nodes=1                   # the number of nodes you want to reserve
#SBATCH --gres=gpu:1 
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16      # CHANGE
#SBATCH --mem=90G           # how much memory is needed per node (units can be: K, M, G, T) # CHANGE
#SBATCH --partition=gpu3090     # on which partition to submit the job # CHANGE
#SBATCH --time=120:00:00             # the max wallclock time (time limit your job will run) # CHANGE
#SBATCH --output=output_VOC_500_augmentation_added.dat   # the file where output is written to (stdout & stderr) # CHANGE
#SBATCH --mail-type=ALL            # receive an email when your job starts, finishes normally or is aborted
#SBATCH --mail-user=jbalzer@uni-muenster.de # your mail address # CHANGE
#SBATCH --nice=50

module purge
module load palma/2021a Miniconda3/4.9.2 # CHANGE

CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda deactivate
conda activate windEnergy # CHANGE


srun --export=ALL python3 nsga.py  # CHANGE
