#!/bin/bash

#SBATCH --job-name=Smart_Repair_100m_full_infinite # The job name # CHANGE
#SBATCH --export=NONE               # Start with a clean environment
#SBATCH --nodes=1                   # the number of nodes you want to reserve
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=35      # CHANGE
#SBATCH --mem=30G           # how much memory is needed per node (units can be: K, M, G, T) # CHANGE
#SBATCH --partition=long   # on which partition to submit the job # CHANGE
#SBATCH --time=85:00:00             # the max wallclock time (time limit your job will run) # CHANGE
#SBATCH --output=output_smart_repair_100_full_infinite.dat   # the file where output is written to (stdout & stderr) # CHANGE
#SBATCH --mail-type=ALL            # receive an email when your job starts, finishes normally or is aborted
#SBATCH --mail-user=jbalzer@uni-muenster.de # your mail address # CHANGE
#SBATCH --nice=50

module --force purge
module load palma/2021a Miniconda3/4.9.2 # CHANGE

CONDA_BASE=$(conda info --base)
source $CONDA_BASE/etc/profile.d/conda.sh
conda deactivate
conda activate study_project # CHANGE #Alternativen: WindEnergy_3_8 WindEnergy


srun --export=ALL python3 Genetic.py Long100Meters full False 34 smart_repair 0.10 100 Josefina --max_base_generations 1400 # CHANGE
